config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root "incidents#index"
  
  resources :incidents, only: [:new, :create, :index, :show]

  get '/about', to: 'incidents#about'

  resources :users, only: [:show, :edit, :update]
  get '/about',   to: 'incidents#about'
  get '/sign-up', to: 'users#new'
  post '/sign-up', to: 'users#create'
  delete '/delete-account', to: 'users#destroy'

  get '/sign-in', to: 'sessions#new'
  post '/sign-in', to: 'sessions#create'
  delete '/sign-out', to: 'sessions#destroy'


end

app/models/incident.rb
require 'google/api_client'
class Incident < ActiveRecord::Base
 
  attr_accessor :address
  belongs_to :user
  mount_uploader :image, ImageUploader
  reverse_geocoded_by :latitude, :longitude


  def get_city_data
    client = CivicAide::Client.new(ENV['GOOGLE_KEY'])
    @results = client.representatives.at(location)
  end

  def get_council 
    get_city_data
    @council = @results["officials"].select do |key, value_hash|
      value_hash["urls"][0].match(/council\.nyc\.gov/) if value_hash["urls"]  
    end 
    @rep_name = @council[@council.keys.first]["name"]
    @number = @council[@council.keys.first]["phones"][0]
    @twitter = "@#{@council[@council.keys.first]["channels"][0]["id"]}"
    @photo_url = @council[@council.keys.first]["photo_url"]
    @email =  @council[@council.keys.first]["emails"][0]
  end

  def get_photo
    get_council
    @photo_url
  end 
  
   def get_name
    get_council
    @rep_name
  end 
  
  def get_email
    get_council
    @email
  end

  def get_number
    get_council
    @number
  end
  def get_twitter
    get_council
    @twitter = "@#{@council[@council.keys.first]["channels"][0]["id"]}"
  end

  def location
    @address = self.reverse_geocode
    # if @address = "5 Beaver Street, New York, NY 10004, USA"
    #   @location = "11 Broadway, New York, NY, 10004"
    # else 
    @location = @address
    # end 
    # @location
  end 

  def zipcode
    @location.match(/(\d{5})/)[1]
  end 


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :incidents
  has_secure_password
  validates :email, presence: true, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authenticate!
    redirect_to root_path, notice: "You must be logged in to do that" unless logged_in?
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController

def about
end   
def index
  @incidents = Incident.all
end 
def new
  @incident = Incident.new
end

def create
  
    @incident = Incident.create(incident_params)
    
    if logged_in?
      @incident.user = current_user 
      @incident.user.incidents << @incident
    end
    @incident.get_city_data 
    IncidentMailer.report_email(@incident).deliver_now!
    redirect_to @incident
 end 
 
  
  def show
    @incident = Incident.find(params[:id])
  end

   

  private
  def incident_params
    params.require(:incident).permit(:name, :description, :image, :latitude, :longitude)
  end 


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You've been signed in"
    else
      @user = User.new
      @user.errors[:base] = "Bad username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have been successfully signed out!"
  end

  private
  def boot_if_logged_in
    redirect_to root_path if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end 
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]  = @user.id
      redirect_to @user, notice: "Your account has been created!"
    else
      @user = User.new
      @user.errors[:base] = "Bad username or password"
      render :new
    end
  end 
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end 

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.erb
<div class="module-small bg-dark">
      <div class="container">
  
        <div class="row">
  
          <div class="col-sm-3">
  
            <!-- Widget start -->
            <div class="widget" role="about-us">
              <h5 class="widget-title font-alt">About Candid Sidewalk</h5>
              <p>Take civic action with the convenience of your smart phone!</p>
            </div>
            <!-- Widget end -->
  
          </div>
  
          <div class="col-sm-3">
  
            <!-- Widget start -->
            <div class="widget" role="recent-incidents">
              <h5 class="widget-title font-alt">Recent Incidents</h5>
              <ul class="icon-list">
                <li>Cracked Sidewalk on <a href="#" aria-label="cracked sidewalk on broadway">Broadway</a></li>
                <li>Trippy bump on <a href="#" aria-label="trippy bump on canal street">Canal Street</a></li>
              </ul>
            </div>
            <!-- Widget end -->
  
          </div>
  
          <div class="col-sm-3">
  
            <!-- Widget start -->
            <div class="widget">
              <h5 class="widget-title font-alt">Resources</h5>
              <ul class="icon-list">
                <li><a href="#">My Account</a></li>
                <li><a href="#">My representives</a></li>
              </ul>
            </div>
            <!-- Widget end -->
  
          </div>
  
          <div class="col-sm-3">
  
            <!-- Widget start -->
            <div class="widget">
              <h5 class="widget-title font-alt">City Open Data</h5>
              <ul class="widget-posts" alt="open-data-websites">
  
                <li class="clearfix" role="new-york-city-open-data">
                  <div class="widget-posts-image">
                    <a href="#"><img src="https://www.iqt.org/wp-content/uploads/2013/09/Socrata_logo_source-40x44.png" alt="NYC Open Data Website"></a>
                  </div>
                  <div class="widget-posts-body">
                    <div class="widget-posts-title">
                      <a href="#">NYC Open Data</a>
                    </div>
                  </div>
                </li>
  
                <li class="clearfix">
                  <div class="widget-posts-image">
                    <a href="#"><img src="http://pbs.twimg.com/profile_images/3057855429/49cff02ea1ea88993d7edadd8b027982_normal.jpeg" alt="Chris Whong"></a>
                  </div>
                  <div class="widget-posts-body">
                    <div class="widget-posts-title">
                      <a href="http://chriswhong.com/">Chris Whong</a>
                    </div>
                  </div>
                </li>
                
                <li class="clearfix">
                  <div class="widget-posts-image">
                    <a href="#"><img src="http://www.unlockphilly.com/images/logo/unlock_logo_aug_14_flipped.png" alt="Unlock Philly"></a>
                  </div>
                  <div class="widget-posts-body">
                    <div class="widget-posts-title">
                      <a href="http://unlockphilly.com/">Unlock Philly</a>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
            <!-- Widget end -->
  
          </div>
  
        </div><!-- .row -->
  
      </div>
    </div>
    <footer class="footer bg-dark">
      <div class="container">
  
        <div class="row">
  
          <div class="col-sm-6">
            <p class="copyright font-alt">© 2015 <a href="#" aria-label="Copyright 2015 and made with love by Team Holy Sidewalks, all rights reserved">Made with &#10084; by Team Holy Sidewalks</a>, All Rights Reserved.</p>
          </div>
  
          <div class="col-sm-6">
            <div class="footer-social-links">
              <a href="#"><i class="fa fa-facebook" aria-label="facebook"></i></a>
              <a href="#"><i class="fa fa-twitter" aria-label="twitter"></i></a>
              <a href="#"><i class="fa fa-github" aria-label="github"></i></a>
              <a href="#"><i class="fa fa-pinterest" aria-label="pinterest"></i></a>
            </div>
          </div>
  
        </div><!-- .row -->
  
      </div>
    </footer>

app/views/application/_nav.html.erb
<div class="col-xs-1">
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
         <%= link_to "Candid Sidewalk", root_path, class: "navbar-brand", title: "Link to main page" %>
      </div>

     
      <div class="collapse navbar-collapse" id="custom-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
           <li >
            <%= link_to "My Account", user_path(current_user) %>
          </li>
          <% end %>

          <li >
            <%= link_to "Report a Sidewalk", new_incident_path %>
          </li>

           <li >
            <%= link_to "About", about_path %>
          </li>
        <% unless logged_in? %>  
          <li >
            <%= link_to "Sign Up", sign_up_path %>
          </li>
          
          <li >
            <%= link_to "Log In", sign_in_path %>
          </li>
        <% else %>
          <li>
            <%= link_to "Log Out", sign_out_path, method: :delete  %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>

  </nav> 
</div>

app/views/incidents/_incident.html.erb
<h1>Congratulations! Your Incident Report has been emailed to representative <%= @incident.get_name %></h1>
<div>
<p><strong>Your location:</strong> <%= @incident.reverse_geocode %>
</p>
</div>
<div>
<h4>
Dear Council Member <%= @incident.get_name %>,<br><br>

Our district’s streets are in dire need of repair. Potholes and  uneven <br> sidwalks are a hazard to our local population, as well as a major barrier <br> for people with disabilities. <br><br>

The image below was taken at <%= @incident.reverse_geocode %>,<br> in this district. Our community deserves safe, repaired streets. Please fix <br> this road, to prevent injury and increase the wellbeing of your constituents. <br>
<br>
<div><%= image_tag(@incident.image, alt: 'Broken Sidewalk') %>
</div>
Signed,<br>
Concerned Citizen
</h4>

 
</div>

app/views/incidents/_preview.html.erb
<p>Dear Council Member,</p>

<p>Our district’s streets are in dire need of repair. Potholes and  uneven sidwalks are a hazard to our local population, as well as a major barrier for people with disabilities.</p>

<p>The image below was taken in this district. Our community deserves safe, repaired streets. Please fix this road, to prevent injury and increase the wellbeing of us, the constituents.</p>

app/views/incidents/_sidebarleft.html.erb
<div class="col-sm-4 sidebar">

  <div class="widget">
    <h5 class="widget-title font-alt"><i class="fa fa-arrow-circle-right"></i> GET STARTED</h5>
    Candid Sidewalk is the shortest distance between you and your local representative. Snap a picture of a hazard in your community, and Candid Sidewalk will send an email with the picture and its location to your local councilperson.
  </div>
  <div>
    <%= link_to "Report Broken Sidewalk!", new_incident_path, class: "btn btn-default"%>
  </div>
</div>

app/views/incidents/about.html.erb
<div class="row">

    <div class="col-sm-6 col-sm-offset-3">

        <h2 class="module-title font-alt">About Candid Sidewalk</h2>
        <div class="module-subtitle font-serif">
            Take civic action with convenience of your smart phone!
        </div>

    </div>

</div>

<div class="row multi-columns-row">

          <!-- Features start -->
          <div class="col-sm-4">

            <div class="features-item">
              <div class="features-icon">
                <span class="icon-phone" aria-label="phone icon"></span>
              </div>
              <h3 class="features-title font-alt">Snap a Sidewalk!</h3>
              <ul class="text-left">
                <li>Take a picture</li> 
                <li>Your phone immediately identifies the exact street address of the culprit crack!</li> 
                <li>Email the local City Council Member of the district you are currently in</li>
              </ul> 
            </div>

          </div>
          <!-- Features end -->

          <!-- Features start -->
          <div class="col-sm-4">

            <div class="features-item">
              <div class="features-icon">
                <span class="icon-map" aria-label="map icon"></span>
              </div>
              <h3 class="features-title font-alt">Viewing Local Streets</h3>
              <ul class="text-left">
                <li>See the condition of your daily routes.</li> 
                <li>View conditions by neighborhood.</li> 
              </ul>
            </div>

          </div>
          <!-- Features end -->

          <!-- Features start -->
          <div class="col-sm-4">

            <div class="features-item">
              <div class="features-icon">
                <span class="icon-clipboard" aria-label="clipboard icon"></span>
              </div>
              <h3 class="features-title font-alt">Record Your Reports</h3>
              <ul class="text-left">
                <li>Keep a record of all of your incidents.</li> 
                <li>Share with friends.</li>
                <li>Keep the local government informed and accountable!</li> 
              </ul>
            </div>

          </div>
    <div class="row spacer"></div>
    <hr class="divider-w">
    <div class="row spacer"></div>

    <div class="row">

    <div class="col-sm-6 col-sm-offset-3">

        <h5 class="module-title font-alt">Meet Our Team</h5>
        
    </div>

  </div>

  <div class="row">

          <!-- Team item star -->
          <div class="col-sm-4 mb-sm-20 wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp; -webkit-animation-name: fadeInUp;">

            <div class="team-item">
              <div class="team-image">
                <img src="<%= image_url('julian.jpg') %>" alt="Julian Taub, Web Developer">
                <div class="team-detail">
                  <div class="team-social">
                    <a href="https://www.facebook.com/julian.taub.5"><i class="fa fa-facebook" aria-label="Julian's facebook"></i></a>
                    <a href="https://twitter.com/JulianTaub"><i class="fa fa-twitter" aria-label="Julian's twitter"></i></a>
                    <a href="https://github.com/JulianTaub"><i class="fa fa-github" aria-label="Julian's github"></i></a>
                    <a href="http://juliantaub.github.io/"><i class="fa fa-rss" aria-label="Julian's blog"></i></a>
                  </div>
                </div>
              </div>
              <div class="team-descr font-alt">
                <div class="team-name">Julian Taub</div>
                <div class="team-role">Web Developer</div>
              </div>
            </div>

          </div>
          <!-- Team item end -->

          <!-- Team item star -->
          <div class="col-sm-4 mb-sm-20 wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp; -webkit-animation-name: fadeInUp;">

            <div class="team-item">
              <div class="team-image">
                <img src="<%= image_url('dana.jpg') %>" alt="Dana Najjar, Web Developer">
                <div class="team-detail">
                  <div class="team-social">
                    <a href="#"><i class="fa fa-facebook" aria-label="Dana's facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-label="Dana's twitter"></i></a>
                    <a href="#"><i class="fa fa-github" aria-label="Dana's github"></i></a>
                    <a href="#"><i class="fa fa-rss" aria-label="Dana's blog"></i></a>
                  </div>
                </div>
              </div>
              <div class="team-descr font-alt">
                <div class="team-name">Dana Najjar</div>
                <div class="team-role">Web Developer</div>
              </div>
            </div>

          </div>
          <!-- Team item end -->

          <!-- Team item star -->
          <div class="col-sm-4 mb-sm-20 wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp; -webkit-animation-name: fadeInUp;">

            <div class="team-item">
              <div class="team-image">
                <img src="<%= image_url('josh.png') %>" alt="Joshua Baker, Web Developer">
                <div class="team-detail">
                  <div class="team-social">
                    <a href="#"><i class="fa fa-facebook" aria-label="Josh's facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-label="Josh's twitter"></i></a>
                    <a href="#"><i class="fa fa-github" aria-label="Josh's github"></i></a>
                    <a href="#"><i class="fa fa-rss" aria-label="Josh's blog"></i></a>
                  </div>
                </div>
              </div>
              <div class="team-descr font-alt">
                <div class="team-name">Joshua Baker</div>
                <div class="team-role">Web Developer</div>
              </div>
            </div>

          </div>
          <!-- Team item end -->

          <!-- Team item star -->
          
          <!-- Team item end -->

        </div>
          

</div>

app/views/incidents/index.html.erb
<%= render "sidebarleft" %>
<h5 class="widget-title font-alt col-sm-8" style="text-align: center;">  REPORTS TO DATE IN NYC: <%=Incident.all.count%>  </h5>
<div id="map-canvas" class="col-sm-8">
  </div>
 


<center>   
<script>    
  function initialize() {

    var mapOptions = {
      center: new google.maps.LatLng(40.7527, -74.0059),
      zoom: 11,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var mapCanvas = document.getElementById('map-canvas');
    var map = new google.maps.Map(mapCanvas, mapOptions);
  <% @incidents.each do |incident|%>
    <%if incident.longitude && incident.latitude%>
      var myLatlng = new google.maps.LatLng(<%= incident.latitude %>,<%= incident.longitude %>);
      
      var marker = new google.maps.Marker({
        position: myLatlng,
        map: map       
    }); 

    <% end %>
     <% end %>

      
  }
  google.maps.event.addDomListener(window, 'load', initialize);


</script>
</center> 

app/views/incidents/new.html.erb
<div class="col-xs-10 col-xs-offset-1 col-xs-6 col-sm-offset-3">
<div id="spin"></div>
<h2>My Sidewalk Image</h2>
<%= form_for @incident do |f| %>
 <p>
   <%= f.label :name%>
   <%= f.text_field :name, class: "form-control" %>
   <%= f.label :description %>
   <%= f.text_field :description, class: "form-control" %>
   <%= f.file_field :image, class: "form-control", :required => true %>
   <%= f.hidden_field :image_cache %>
   <%= f.submit "Send Report", class: "btn btn-block btn-round btn-d" %>
 </p>
<% end %>
<button id="preview" >Preview Image</button>
<div class="preview">  
  </div>
</div>

<script>
  $(document).ready(function(){    
  $('form').submit(function(e){

     e.preventDefault();
  function getLocation() {
    if (navigator.geolocation) {
     navigator.geolocation.getCurrentPosition(showPosition);
    }
  }
 
  function showPosition(position) {
        var longitude = position.coords.longitude;
        var latitude = position.coords.latitude;
        var location = [latitude, longitude];
       
       $('form').children().append('<input type="hidden" name="incident[latitude]" value=' + latitude + ' >');
       $('form').children().append('<input type="hidden" name="incident[longitude]" value=' + longitude + ' >');
       $('form').children().append('<input type="hidden" name="incident[location]" value=' + location + ' >');
   

        $('form').unbind('submit').submit();

    };

      getLocation(); 
       $("#spin").show(); 
  });

var opts = {
  lines: 17, // The number of lines to draw
  length: 0, // The length of each line
  width: 10, // The line thickness
  radius: 50, // The radius of the inner circle
  corners: 1, // Corner roundness (0..1)
  rotate: 29, // The rotation offset
  direction: 1, // 1: clockwise, -1: counterclockwise
  color: '#669999', // #rgb or #rrggbb or array of colors
  speed: 1.4, // Rounds per second
  trail: 10, // Afterglow percentage
  shadow: false, // Whether to render a shadow
  hwaccel: false, // Whether to use hardware acceleration
  className: 'spinner', // The CSS class to assign to the spinner
  zIndex: 2e9, // The z-index (defaults to 2000000000)
  top: '50%', // Top position relative to parent
  left: '49.5%' // Left position relative to parent
  };
var target = document.getElementById('spin');
var spinner = new Spinner(opts).spin(target);
$('#spin').hide();

 })

</script>

app/views/incidents/show.html.erb
<div>
<%= render 'incident' %>
</div>

<!-- 
<script>    
  function initialize() {
    var mapOptions = {
      center: new google.maps.LatLng(40.7527, -74.0059),
      zoom: 11,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var mapCanvas = document.getElementById('map');
    var myLatlng = new google.maps.LatLng(<%=@incident.latitude%>,<%= @incident.longitude%>);
    var map = new google.maps.Map(mapCanvas, mapOptions);
        var marker = new google.maps.Marker({
        position: myLatlng,
        map: map       
        });  
  }
  google.maps.event.addDomListener(window, 'load', initialize);

</script> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<script src="https://maps.googleapis.com/maps/api/js"></script>
 <%= javascript_include_tag '//fgnass.github.io/spin.js/spin.min.js' %>
  <title>CandidSidewalk</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'nav' %>
  <div class="container">
    <h5 class="notice"><%= notice %></h5>  
    <%= yield %>
  </div>
      <div id="footer">
      <%= render 'footer' %>
    </div>
</body>
</html>

app/views/users/index.html.erb
index.html.erb

app/views/users/new.html.erb
<div class="col-xs-6 col-xs-offset-3">
  <% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>
  <h2>Sign up</h2>

  <%= form_for @user, url: sign_up_path do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"  %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control"  %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control"  %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control"  %>
    </div>
    <%= f.submit "Create your account", class: "btn btn-block btn-round btn-d"  %>
  <% end %>
</div>

app/views/users/show.html.erb
<h3 style="text-align: center;"><%= @user.name.capitalize %>'s Account</h3>

<h4 style="text-align: center;"><%=@user.incidents.count%> Reported Incidents:</h4>
<div class="col-sm-6" stle="height: 200px;">
<ul id="works-grid" class="works-grid works-grid-gut works-grid-3 works-hover-w" style="position: relative; height: 300px;">
<% @user.incidents.each do |incident| %>
        <!-- Portfolio item start -->
        <li class="work-item illustration webdesign">
            <div class="work-image">
            <%= image_tag(incident.image.thumb, alt: "Report Image") %>
            </div>
            <div class="work-caption font-alt">
              <h3 class="work-title"> <%= incident.name %></h3>
              
            </div>
            <div>
                  <%= incident.location %>
              </div>
        </li>
    <% end %>
      </ul>
  </div>
  <div id="map-canvas1" class="col-sm-6">
  </div>
  <script>    
  function initialize() {

    var mapOptions = {
      center: new google.maps.LatLng(40.7527, -74.0059),
      zoom: 11,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var mapCanvas = document.getElementById('map-canvas1');
    var map = new google.maps.Map(mapCanvas, mapOptions);
  
  <% @user.incidents.each do |incident|%>
    <% if incident.latitude && incident.longitude%> 
      var myLatlng = new google.maps.LatLng(<%= incident.latitude %>,<%= incident.longitude %>);
      
      var marker = new google.maps.Marker({
        position: myLatlng,
        map: map       
    }); 
      <% end %>
    <% end %>
      
  }
  google.maps.event.addDomListener(window, 'load', initialize);


</script>